/* Turkish (Türkçe) translation. Keys are the English texts used in the game.
   Vocabulary: Heat = Şüphe, stewards = komiserler, Reputation = İtibar (İP), backroom = arka oda, slip = kupon. */
(function () {
  Object.assign(I18n.dict.tr, {
    "Suit Derby": "Suit Derby",
    "Menu": "Menü",
    "Permanent upgrades": "Kalıcı geliştirmeler",
    "Rules": "Kurallar",
    "Language": "Dil",
    "Sound on": "Ses açık",
    "Sound off": "Ses kapalı",
    "Music on": "Müzik açık",
    "Music off": "Müzik kapalı",
    "Length": "Uzunluk",
    "Horse": "At",
    "Main menu": "Ana menü",
    "Race": "Yarış",
    "Stake": "Bahis",
    "Resume": "Devam",
    "Skip": "Geç",
    "Call the order": "Sıralamayı tahmin et",
    "Really reset everything?": "Gerçekten her şey sıfırlansın mı?",
    "BIG WIN": "BÜYÜK KAZANÇ",
    "MEGA WIN": "MEGA KAZANÇ",
    "JACKPOT": "JACKPOT",
    "You": "Sen",
    "start with {m}": "{m} ile başla",
    "{n} cards": "{n} kart",
    "home": "bitiş",
    "likeliest": "en olası",
    "PERFECT": "KUSURSUZ",
    "tails": "yazı",
    "GO": "BAŞLA",
    "miss": "ıska",
    "Buy": "Al",
    "higher": "daha yüksek",
    "{m} at stake": "{m} bahiste",
    "Level {n} / {m}": "Seviye {n} / {m}",
    "Maxed": "Maksimum",
    "Deck": "Deste",
    "Money": "Para",
    "Hearts": "Kupa",
    "Diamonds": "Karo",
    "Clubs": "Sinek",
    "Spades": "Maça",
    "Haggler": "Pazarlıkçı",
    "High Roller": "Büyük Oyuncu",
    "Deep Pockets": "Dolu Cepler",
    "Derby Day": "Derbi Günü",
    "The race": "Yarış",
    "Stakes": "Zorluk",
    "How to play": "Nasıl oynanır",
    "none": "yok",
    "Got it": "Anladım",
    "Next": "İleri",
    "Result": "Sonuç",
    "Safety Net": "Güvenlik Ağı",
    "High Stakes": "Yüksek Bahisler",
    "Gambler": "Kumarbaz",
    "Open a neighbouring node first": "Önce komşu bir düğümü aç",
    "Owned": "Sahipsin",
    "Not owned": "Sahip değilsin",
    "unlocked": "açık",
    "trophy": "rozet",
    "Track": "Pist",
    "Wheel of Fortune": "Kader Çarkı",
    "Skill tree": "Yetenek ağacı",
    "Back": "Geri",
    "Use": "Kullan",
    "Tap a node to see what it does. You start in the middle and the tree grows as you buy: new nodes appear next to the ones you own.": "Ne işe yaradığını görmek için bir düğüme dokun. Ortadan başlarsın ve ağaç sen satın aldıkça büyür: yeni düğümler sahip olduklarının yanında belirir.",
    "Lane Swap": "Koridor Değişimi",
    "Peek": "Göz At",
    "Look at the next card before it is drawn. The book does not know it.": "Çekilmeden önce sıradaki karta bak. Defter bunu bilmiyor.",
    "Burn": "Yak",
    "Throw the next card away. Nobody moves.": "Sıradaki kartı at. Kimse ilerlemez.",
    "Stack": "Üste Çek",
    "Pull the nearest card of a suit to the top of the deck.": "Bir takımın en yakın kartını destenin üstüne çek.",
    "Mud": "Çamur",
    "Soak a lane: the horse loses 1 step on its next 3 cards.": "Bir koridoru ıslat: at sonraki 3 kartında 1 adım kaybeder.",
    "Swap": "Değiştir",
    "Swap the top two cards of the deck.": "Destenin üstündeki iki kartın yerini değiştir.",
    "Tailwind": "Arkadan Rüzgâr",
    "A gust behind a horse: +1 step on its next 3 cards.": "Atın arkasından esen bir rüzgâr: sonraki 3 kartında +1 adım.",
    "Shave": "Kırp",
    "Quietly remove one plain card of a suit from the deck for good.": "Bir takımın bir sayı kartını sessizce desteden kalıcı olarak çıkar.",
    "Hurdle": "Engel",
    "Drop a hurdle: the horse wastes its next card.": "Bir engel koy: at sıradaki kartını boşa harcar.",
    "Riffle": "Karıştır",
    "Reshuffle the whole deck. Good when the cards are running against you.": "Bütün desteyi yeniden karıştır. Kartlar aleyhine giderken işe yarar.",
    "The horse trades places with the one just ahead of it. Once a night.": "At, hemen önündeki atla yer değiştirir. Gecede bir kez.",
    "Tool Discount": "Araç İndirimi",
    "Every tool costs 20% less.": "Her araç %20 daha ucuz.",
    "Ice Bucket": "Buz Kovası",
    "Heat cools twice as fast.": "Şüphe iki kat hızlı soğur.",
    "Lookout": "Gözcü",
    "The stewards spot you 30% less often.": "Komiserler seni %30 daha az fark eder.",
    "Binoculars": "Dürbün",
    "Peek shows one more card.": "Göz At bir kart daha gösterir.",
    "Friendly Bookie": "Dost Bahisçi",
    "Better odds: the book keeps 4% less.": "Daha iyi oranlar: defter %4 daha az pay alır.",
    "High Roller Table": "Yüksek Bahis Masası",
    "A perfect order pays 1 more times the stake.": "Kusursuz sıralama bahsin 1 katı daha fazla öder.",
    "Late Money": "Geç Para",
    "Re-calls cost half as much.": "Tahmin değişikliği yarı fiyata.",
    "Bigger Toolbelt": "Büyük Alet Kemeri",
    "One more use of every tool each race.": "Her yarışta her aracın bir kullanımı daha.",
    "Greased Palm": "Yağlı Avuç",
    "The first tool you use each race adds no Heat.": "Her yarışta kullandığın ilk araç Şüphe artırmaz.",
    "Tip-off": "Gizli Bilgi",
    "The top card of every deck is shown before you call.": "Tahmin etmeden önce her destenin üst kartı gösterilir.",
    "If no place of yours hits, get 30% of your stakes back.": "Hiçbir sıran tutmazsa bahislerinin %30’unu geri al.",
    "Good Lawyer": "İyi Avukat",
    "Fines are 40% smaller.": "Cezalar %40 daha küçük.",
    "Unlocks the Swap tool: swap the top two cards.": "Değiştir aracını açar: üstteki iki kartı değiştir.",
    "Unlocks the Tailwind tool: a horse gets +1 step on its next 3 cards.": "Arkadan Rüzgâr aracını açar: bir at sonraki 3 kartında +1 adım alır.",
    "Unlocks the Shave tool: remove a plain card of a suit for good.": "Kırp aracını açar: bir takımın bir sayı kartını kalıcı olarak çıkar.",
    "Unlocks the Hurdle tool: a horse wastes its next card.": "Engel aracını açar: bir at sıradaki kartını boşa harcar.",
    "Unlocks the Riffle tool: reshuffle the deck.": "Karıştır aracını açar: desteyi yeniden karıştır.",
    "Unlocks Lane Swap: a horse trades places with the one just ahead. Once a night.": "Koridor Değişimi’ni açar: bir at, hemen önündeki atla yer değiştirir. Gecede bir kez.",
    "Deep Toolbox": "Derin Alet Çantası",
    "One more use of every tool in every race.": "Her yarışta her aracın bir kullanımı daha.",
    "Cool Head": "Soğukkanlılık",
    "Heat cools 25% faster.": "Şüphe %25 daha hızlı soğur.",
    "Thick Skin": "Kalın Deri",
    "You can carry 1 more Heat before you are caught.": "Yakalanmadan önce 1 Şüphe daha taşıyabilirsin.",
    "Friend on the Board": "Kurulda Bir Dost",
    "Stewards spot you 15% less often.": "Komiserler seni %15 daha az fark eder.",
    "Lawyer": "Avukat",
    "Fines are 20% smaller.": "Cezalar %20 daha küçük.",
    "The first tool you use in each race adds no Heat.": "Her yarışta kullandığın ilk araç Şüphe artırmaz.",
    "Alibi": "Mazeret",
    "If you are caught, you get half of your stakes back.": "Yakalanırsan bahislerinin yarısını geri alırsın.",
    "Start every night with $30 more.": "Her geceye $30 fazla parayla başla.",
    "Unlocks the $100 chip.": "$100’lık fişi açar.",
    "Every tool costs 5% less.": "Her araç %5 daha ucuz.",
    "Long Night": "Uzun Gece",
    "Lets you choose a night of 8 races.": "8 yarışlık bir gece seçmene izin verir.",
    "Shark’s Terms": "Tefeci Şartları",
    "A loan costs $10 less to pay back.": "Bir borcu ödemek $10 daha ucuz.",
    "If no place hits, 15% of your stakes come back.": "Hiçbir sıra tutmazsa bahislerinin %15’i geri gelir.",
    "Sharp Eye": "Keskin Göz",
    "Better odds: the book keeps 1% less.": "Daha iyi oranlar: defter %1 daha az pay alır.",
    "Perfect Pay": "Kusursuz Ödeme",
    "A perfect order pays half a stake more.": "Kusursuz sıralama yarım bahis daha fazla öder.",
    "Backroom Network": "Arka Oda Ağı",
    "One more favor on offer in the backroom.": "Arka odada bir iyilik daha sunulur.",
    "Re-calls cost 25% less.": "Tahmin değişikliği %25 daha ucuz.",
    "Toolbox": "Alet Çantası",
    "Nerve": "Cesaret",
    "Bankroll": "Kasa",
    "The Book": "Bahis Defteri",
    "Not unlocked yet. Open it in Reputation.": "Henüz açılmadı. İtibar’dan aç.",
    "You are out of this race.": "Bu yarışın dışındasın.",
    "The stewards took it.": "Komiserler aldı.",
    "No uses left this race.": "Bu yarış için kullanım kalmadı.",
    "Used up for tonight.": "Bu gece için bitti.",
    "Not enough cash.": "Yeterli para yok.",
    "Not now.": "Şimdi olmaz.",
    "No such card left.": "Öyle bir kart kalmadı.",
    "It is already on top.": "Zaten en üstte.",
    "Both cards are the same suit.": "İki kart da aynı takımdan.",
    "That horse has already finished.": "O at zaten bitirdi.",
    "That horse is already in front.": "O at zaten önde.",
    "The deck is empty.": "Deste boş.",
    "Pick a target first.": "Önce bir hedef seç.",
    "You peek at the top of the deck.": "Destenin üstüne göz atıyorsun.",
    "A card goes in the bin.": "Bir kart çöpe gidiyor.",
    "The top two cards swap places.": "Üstteki iki kart yer değiştiriyor.",
    "A {s} card is on top now.": "Artık üstte bir {s} kartı var.",
    "A plain {s} card quietly disappears.": "Bir {s} sayı kartı sessizce ortadan kayboluyor.",
    "The deck is reshuffled.": "Deste yeniden karıştırıldı.",
    "Mud in the {s} lane.": "{s} koridorunda çamur var.",
    "A tailwind for {s}.": "{s} için arkadan rüzgâr.",
    "A hurdle in front of {s}.": "{s} önünde bir engel.",
    "{s} slips past {o}.": "{s}, {o} atını geçiyor.",
    "Calm": "Sakin",
    "Warm": "Isınıyor",
    "The stewards are watching": "Komiserler izliyor",
    "Danger": "Tehlike",
    "Your bankroll. What is left at the end of the night is your score.": "Kasan. Gecenin sonunda kalan paran puanındır.",
    "owe {m}": "borç {m}",
    "Heat": "Şüphe",
    "Heat {h} of {c}": "Şüphe {h} / {c}",
    "{p} inspection chance": "{p} denetim şansı",
    "Race {n} of {m}": "Yarış {n} / {m}",
    "in the backroom": "arka odada",
    "Gambler’s Night": "Kumarbazın Gecesi",
    "{n} RP": "{n} İP",
    "You are not an owner tonight. You are a gambler with a pocket full of tricks. Call the order all four horses will finish in, then bend the deck and the track your way. Do not get caught.": "Bu gece at sahibi değilsin. Cebi hilelerle dolu bir kumarbazsın. Dört atın bitireceği sırayı tahmin et, sonra desteyi ve pisti kendi yoluna çevir. Yakalanma.",
    "Read": "Oku",
    "Study the deck sheet. Every card moves one horse. More cards means more steps, and the odds come from the cards.": "Deste kâğıdını incele. Her kart bir atı ilerletir. Daha çok kart daha çok adım demek ve oranlar kartlardan gelir.",
    "Call": "Tahmin Et",
    "Pick a horse for each place, then lock your slip before the first card. Odds lock with it.": "Her sıra için bir at seç, sonra ilk karttan önce kuponunu kilitle. Oranlar onunla birlikte kilitlenir.",
    "Rig": "Hile Yap",
    "Cards are time. Between draws, spend cash on tools that nudge the deck or the track.": "Kartlar zamandır. Çekişler arasında desteyi ya da pisti dürten araçlara para harca.",
    "Stay clean": "Temiz Kal",
    "Every trick adds Heat. Too much and the stewards inspect you, fine you, or throw out your slip.": "Her hile Şüphe artırır. Fazlası olursa komiserler seni denetler, ceza keser ya da kuponunu iptal eder.",
    "Length of the night": "Gecenin uzunluğu",
    "Unlock “Long Night” in Reputation": "İtibar’da “Uzun Gece”yi aç",
    "A short night": "Kısa bir gece",
    "A long night": "Uzun bir gece",
    "You start with {m}. What you hold at the end of the night, minus any debt, is your score, and it earns Reputation Points (RP).": "{m} ile başlarsın. Gecenin sonunda elindeki para, borçlar çıkınca, puanındır ve İtibar Puanı (İP) kazandırır.",
    "Starting a new night replaces your saved night.": "Yeni bir gece başlatmak kayıtlı gecenin yerine geçer.",
    "Start the night": "Geceyi başlat",
    "Reputation": "İtibar",
    "{n} plain": "{n} sayı kartı",
    "{n} face": "{n} resimli",
    "Top of the deck": "Destenin üstü",
    "The deck": "Deste",
    "First to {n} steps crosses the line. A plain card moves its horse 1 step, a face card 2. The race ends when 3 horses have crossed. The order of the cards is the only secret.": "İlk {n} adıma ulaşan çizgiyi geçer. Sayı kartı atını 1, resimli kart 2 adım ilerletir. Yarış 3 at çizgiyi geçince biter. Tek sır kartların sırası.",
    "Stake per place": "Sıra başına bahis",
    "{n} places · {m} at stake": "{n} sıra · {m} bahis",
    "Pick a horse for each place you want to back. A horse can hold one place.": "Bahis oynamak istediğin her sıra için bir at seç. Bir at tek sırada olabilir.",
    "Not enough cash for that. Pick a smaller chip or back fewer places.": "Buna yetecek para yok. Daha küçük bir fiş seç ya da daha az sıraya oyna.",
    "Perfect order: {c} chance, pays {m} extra": "Kusursuz sıralama: {c} şans, ekstra {m} öder",
    "Fill with the likeliest order": "En olası sıralamayla doldur",
    "Peek · {m}": "Göz At · {m}",
    "Lock in your call": "Tahminini kilitle",
    "Odds lock when you do. After that you can still change a pick, for a fee, at the odds of that moment.": "Sen kilitleyince oranlar da kilitlenir. Sonrasında bir seçimi, ücret karşılığında, o anın oranıyla yine de değiştirebilirsin.",
    "You are broke: not enough for even the smallest chip. Borrow in the backroom next time, or walk out now.": "Parasızsın: en küçük fişe bile yetmiyor. Bir dahaki sefere arka odadan borç al ya da şimdi çık.",
    "Walk out with {m}": "{m} ile çık",
    "Slip locked. The race is on.": "Kupon kilitlendi. Yarış başladı.",
    "Last card": "Son kart",
    "Your slip": "Kuponun",
    "Tools": "Araçlar",
    "Track talk": "Pist sohbeti",
    "Caught! Your slip is void for this race. The cards are still going to run it out.": "Yakalandın! Kuponun bu yarış için geçersiz. Kartlar yine de yarışı bitirecek.",
    "See the result": "Sonucu gör",
    "Draw a card": "Kart çek",
    "Stop": "Dur",
    "Auto": "Otomatik",
    "Fast": "Hızlı",
    "no bet": "bahis yok",
    "void": "geçersiz",
    "now {p}": "şimdi {p}",
    "Cancel": "Vazgeç",
    "Change": "Değiştir",
    "Change place {p} for a {f} fee, at the odds of now:": "{p} sırayı {f} ücretle, şimdiki oranla değiştir:",
    "Cash {m} · slip {s} · re-calls cost a fee each": "Para {m} · kupon {s} · her değişiklik ücretli",
    "Heat +{h}": "Şüphe +{h}",
    "locked": "kilitli",
    "Steward inspection! Fine {m}, and the {t} is confiscated.": "Komiser denetimi! {m} ceza ve {t} aracına el konuldu.",
    "INSPECTION": "DENETİM",
    "CAUGHT! Disqualified, fined {m}. Your slip is void.": "YAKALANDIN! Diskalifiye, {m} ceza. Kuponun geçersiz.",
    "Your alibi returns {m}.": "Mazeretin {m} geri getiriyor.",
    "CAUGHT": "YAKALANDIN",
    "{s} wastes a card on the hurdle.": "{s} bir kartı engelde harcıyor.",
    "{s} crosses the line: {p}.": "{s} çizgiyi geçiyor: {p}.",
    "The race is over.": "Yarış bitti.",
    "Auto stopped: the odds moved.": "Otomatik durdu: oranlar değişti.",
    "Place {p} switched to {s}.": "{p} sıra {s} olarak değiştirildi.",
    "PERFECT ORDER": "KUSURSUZ SIRALAMA",
    "Caught and disqualified: your slip was void.": "Yakalandın ve diskalifiye oldun: kuponun geçersizdi.",
    "Finishing order": "Bitiş sırası",
    "called ×{o}": "tahmin ×{o}",
    "you had {s}": "seninki {s}",
    "Your night so far": "Şimdiye kadar gecen",
    "Winning calls": "Tutan tahminler",
    "Perfect order": "Kusursuz sıralama",
    "Safety net": "Güvenlik ağı",
    "Re-call fees": "Değişiklik ücretleri",
    "Fines": "Cezalar",
    "Net this race": "Bu yarışın net kazancı",
    "Count up the night": "Geceyi say",
    "To the backroom": "Arka odaya",
    "The backroom": "Arka oda",
    "Between races the fixers sell favors that last the whole night. You may buy one favor. Everything costs cash, and cash is your score.": "Yarışlar arasında hilebazlar bütün gece süren iyilikler satar. Bir iyilik alabilirsin. Her şey paradır ve para puanındır.",
    "Favor": "İyilik",
    "Services": "Hizmetler",
    "Service": "Hizmet",
    "Cool off": "Soğu",
    "Slip out for a while. Heat drops by {n}.": "Bir süre ortadan kaybol. Şüphe {n} düşer.",
    "Loan shark": "Tefeci",
    "Borrow {a} now, owe {o} when the night ends. Twice a night at most.": "Şimdi {a} borç al, gece bitince {o} öde. Gecede en fazla iki kez.",
    "Borrow": "Borç al",
    "Your favors:": "İyiliklerin:",
    "Start race {n}": "{n}. yarışı başlat",
    "Night over": "Gece bitti",
    "You walked out ahead.": "Önde çıktın.",
    "You broke even.": "Başa baş çıktın.",
    "The house had a good night.": "Kasa iyi bir gece geçirdi.",
    "Cash at the end": "Sondaki para",
    "Debt repaid": "Ödenen borç",
    "Final bankroll": "Son kasa",
    "Places called right": "Doğru tahmin edilen sıralar",
    "Perfect orders": "Kusursuz sıralamalar",
    "Tools used": "Kullanılan araçlar",
    "Times caught · inspections": "Yakalanma · denetim",
    "Reputation earned": "Kazanılan itibar",
    "Another night": "Bir gece daha",
    "Reputation Points come from your nights. Spend them on a skill tree that grows as you buy: new tools, a cooler head, a fatter bankroll, a better book.": "İtibar Puanları gecelerinden gelir. Satın aldıkça büyüyen bir yetenek ağacına harca: yeni araçlar, soğukkanlılık, dolgun bir kasa, daha iyi bir defter.",
    "Buy · {c} RP": "Al · {c} İP",
    "Reset Reputation": "İtibarı sıfırla",
    "{n} race": "{n} yarış",
    "{n} races": "{n} yarış",
    "{n} step in the deck": "destede {n} adım",
    "{n} steps in the deck": "destede {n} adım",
    "{n} card drawn": "{n} kart çekildi",
    "{n} cards drawn": "{n} kart çekildi",
    "{n} card left": "{n} kart kaldı",
    "{n} cards left": "{n} kart kaldı",
    "{n} use left": "{n} kullanım kaldı",
    "{n} uses left": "{n} kullanım kaldı",
    "Continue night": "Geceye devam et",
    "All tools and Heat": "Bütün araçlar ve Şüphe",
    "once a night": "gecede bir kez",
    "{n} per race": "yarışta {n}",
    "Heat cools a little with every card drawn without a trick, and between races. From {w} Heat every trick risks a steward inspection: a fine, and the tool is taken away. At {c} Heat you are caught: your slip is void and you are fined.": "Şüphe, hile yapmadan çekilen her kartla ve yarışlar arasında biraz soğur. {w} Şüpheden sonra her hile komiser denetimi riski taşır: ceza ve aracın elinden alınması. {c} Şüphede yakalanırsın: kuponun geçersiz olur ve ceza kesilir.",
    "Call the finishing order, rig the race, don’t get caught.": "Varış sırasını tahmin et, yarışı ayarla, yakalanma.",
    "Four suits race through one deck. Call the order, rig the race, keep your nerve.": "Dört renk tek bir desteyle yarışır. Sırayı tahmin et, yarışı ayarla, soğukkanlılığını koru.",
    "How a night works": "Bir gece nasıl işler",
    "Permanent upgrades · {n} RP": "Kalıcı geliştirmeler · {n} İP",
    "{n} nights · best {p}": "{n} gece · en iyi {p}",
    "No nights yet.": "Henüz gece yok.",
    "One deck, four horses": "Tek deste, dört at",
    "You own no horse tonight. Four horses, one per suit, race through one shuffled deck. Every card drawn moves the horse of that suit one step, or two on a face card.": "Bu gece senin atın yok. Her renkten bir at olmak üzere dört at, karıştırılmış tek bir desteyle yarışır. Çekilen her kart o rengin atını bir adım, resimli kartsa iki adım ilerletir.",
    "There is no clock. Time only moves when a card is drawn.": "Saat yok. Zaman yalnızca bir kart çekildiğinde ilerler.",
    "Before the first card, pick which horse finishes in each place and put chips on it. The odds come from the cards left in the deck, so read the deck sheet.": "İlk karttan önce hangi atın hangi sırada bitireceğini seç ve üzerine fiş koy. Oranlar destede kalan kartlardan gelir, o yüzden deste tablosunu oku.",
    "Lock your slip and the odds are fixed. A perfect order pays a big bonus.": "Kuponunu kilitlediğinde oranlar sabitlenir. Kusursuz sıralama büyük bir bonus öder.",
    "Rig the race": "Yarışı ayarla",
    "While the cards fall you can spend cash on tools: peek at the next card, burn it, stack the deck, soak a lane in mud, give a horse a tailwind.": "Kartlar düşerken araçlara para harcayabilirsin: sıradaki karta göz at, yak, desteyi diz, bir şeridi çamurla, bir ata arkadan rüzgâr ver.",
    "Every trick costs money, and most of them cost Heat.": "Her hile para ister, çoğu da Şüphe artırır.",
    "Mind the Heat": "Şüpheye dikkat",
    "Heat cools a little with every clean card. Past the warning mark, each trick can bring a steward inspection: a fine, and the tool is taken.": "Şüphe, her temiz kartla biraz soğur. Uyarı çizgisinin ötesinde her hile bir komiser denetimi getirebilir: ceza kesilir ve araç elinden alınır.",
    "Reach the cap and you are caught: that race’s slip is void.": "Sınıra ulaşırsan yakalanırsın: o yarışın kuponu geçersiz olur.",
    "Back room, back home": "Arka oda, eve dönüş",
    "Between races you can buy a favor, cool off or borrow. What you hold when the night ends is your score.": "Yarışlar arasında iyilik satın alabilir, soğuyabilir ya da borç alabilirsin. Gece bittiğinde elindeki para skorundur.",
    "Every night earns Reputation Points for permanent upgrades. Your night is saved after every move.": "Her gece, kalıcı geliştirmeler için İtibar Puanı kazandırır. Gecen her hamleden sonra kaydedilir.",
    "unlock in Reputation": "İtibar’dan açılır",
    "A night": "Bir gece",
    "You own no horse. Tonight you are a gambler: a night is a few races, and for each one you call the order all four horses will finish in, stake chips on it, and then run the race card by card. You start with {m}. What you hold when the night ends, minus any debt, is your score, and it earns Reputation Points.": "Senin atın yok. Bu gece bir kumarbazsın: bir gece birkaç yarıştan oluşur; her yarış için dört atın bitireceği sırayı tahmin eder, üzerine fiş koyar, sonra yarışı kart kart oynarsın. {m} ile başlarsın. Gece bittiğinde elindeki para, borçlar düşülerek, skorundur ve İtibar Puanı kazandırır.",
    "Cards are time": "Kartlar zamandır",
    "There is no clock. Time only moves when a card is drawn: the horse of that suit steps forward once, or twice on a face card (J, Q, K, A). The track is {t} steps long and the race is over when three horses have crossed the line; the fourth is placed by how far it got.": "Saat yok. Zaman yalnızca bir kart çekildiğinde ilerler: o rengin atı bir adım, resimli kartta (V, K, P, A) iki adım ilerler. Pist {t} adım uzunluğundadır ve üç at çizgiyi geçince yarış biter; dördüncü, ne kadar ilerlediğine göre sıralanır.",
    "Every race has its own shuffled deck, and drawn cards are never put back. Each suit holds 8 to 11 plain cards and 1 or 2 face cards. The deck sheet on the call screen shows what is left, so you can read which horses the deck favors.": "Her yarışın kendi karıştırılmış destesi vardır ve çekilen kartlar geri konmaz. Her renkte 8 ila 11 sayı kartı ve 1 ya da 2 resimli kart bulunur. Tahmin ekranındaki deste tablosu kalanları gösterir; böylece deste hangi atları tutuyor görebilirsin.",
    "Calling the order": "Sıralamayı tahmin etme",
    "Choose a horse for each place you want to back, and a chip size ({c}). The odds are the exact chance from the cards still in the deck, minus the book’s cut of about {cut}%, so safe picks pay little and long shots pay a lot.": "Oynamak istediğin her sıra için bir at ve bir fiş boyutu ({c}) seç. Oranlar, destede kalan kartlardan hesaplanan kesin şanstır; buradan bahisçinin yaklaşık %{cut} payı düşülür. Güvenli seçimler az, uzun şanslar çok öder.",
    "Back all four places and get them all right and a <b>perfect order</b> bonus is paid on top: the longer the shot, the bigger it is. <b>Fill with the likeliest order</b> picks the most probable finish for you.": "Dört sırayı da oynayıp hepsini doğru bilirsen üstüne <b>kusursuz sıralama</b> bonusu ödenir: şans ne kadar uzaksa bonus o kadar büyüktür. <b>En olası sıralamayla doldur</b> senin için en olası bitişi seçer.",
    "Locking and re-calls": "Kilitleme ve yeniden tahmin",
    "Lock your slip before the first card: the stakes are paid and the odds are fixed. You can still change a pick while the race runs, but every re-call costs {f}% of that slip’s stake and is priced at the odds of that moment. A place that is already decided cannot be changed.": "Kuponunu ilk karttan önce kilitle: bahisler ödenir ve oranlar sabitlenir. Yarış sürerken bir seçimi yine değiştirebilirsin, ama her yeniden tahmin o kuponun bahsinin %{f} kadar tutar ve o anın oranıyla fiyatlanır. Sonuçlanmış bir sıra değiştirilemez.",
    "Between cards you can spend cash on tools that bend the deck or the track. Every tool has a price, a limit per race and a Heat cost. More tools unlock in Reputation.": "Kartlar arasında desteyi ya da pisti eğen araçlara para harcayabilirsin. Her aracın bir fiyatı, yarış başına bir sınırı ve bir Şüphe bedeli vardır. Daha fazla araç İtibar’da açılır.",
    "Heat and the stewards": "Şüphe ve komiserler",
    "Every trick adds Heat. It cools a little with every card drawn clean and between races. From {w} Heat each trick can bring a steward inspection: a fine, and the tool is taken away. At {c} Heat you are caught: that race’s slip is void and you are fined. Tools that only look add no Heat.": "Her hile Şüphe artırır. Hilesiz çekilen her kartla ve yarışlar arasında biraz soğur. {w} Şüpheden itibaren her hile bir komiser denetimi getirebilir: ceza kesilir ve araç elinden alınır. {c} Şüpheye ulaşırsan yakalanırsın: o yarışın kuponu geçersiz olur ve ceza yersin. Yalnızca bakan araçlar Şüphe eklemez.",
    "After every race you visit the backroom. Buy one <b>favor</b> from the offers (it lasts the whole night: cheaper tools, faster cooling, better odds and more), pay {p} to cool off by {a} Heat, or take a loan of {l} that you repay with {o} at the end of the night (two loans at most).": "Her yarıştan sonra arka odaya uğrarsın. Sunulanlardan bir <b>iyilik</b> satın al (bütün gece sürer: daha ucuz araçlar, daha hızlı soğuma, daha iyi oranlar ve fazlası), {a} Şüphe soğutmak için {p} öde ya da gece sonunda {o} ile geri ödeyeceğin {l} borç al (en fazla iki borç).",
    "When the night ends you earn Reputation Points: for your profit, for every place you called right, and a big bonus for each perfect order. Spend them in the Reputation tree on new tools, more chips, a bigger bankroll, cooler nerves and a sharper eye on the book. Nothing in it is lost between nights.": "Gece bittiğinde kârın, doğru bildiğin her sıra ve her kusursuz sıralama için büyük bir bonus olarak İtibar Puanı kazanırsın. Bunları İtibar ağacında yeni araçlara, daha fazla fişe, daha kalın bir kasaya, daha soğuk bir kafaya ve bahisçiye karşı daha keskin bir göze harcarsın. Geceler arasında hiçbir şey kaybolmaz.",
    "Walking out and coming back": "Çekilmek ve geri dönmek",
    "Between races, before you lock a slip, you can walk out and keep what you have. The night is saved after every move: close the page and press Continue night on the menu.": "Yarışlar arasında, bir kuponu kilitlemeden önce masadan kalkıp elindekini koruyabilirsin. Gece her hamleden sonra kaydedilir: sayfayı kapat ve menüden Geceye devam et’e bas."
  });
})();
