/* Turkish (Türkçe) translation. Keys are the English texts used in the game.
   Vocabulary: suit = renk, run = koşu, lap = tur, surge = atılım, stamina = dayanıklılık,
   Spur = Mahmuz, Stable = Ahır, Stable Points = Ahır Puanı (AP). */
(function () {
  const tr = {
    // --- static screens
    'Suit Derby': 'Suit Derby',
    'Menu': 'Menü',
    'Four suits race through one deck. Rig the deck, win the run.': 'Dört renk tek bir desteyle yarışır. Desteyi ayarla, koşuyu kazan.',
    'Play': 'Oyna',
    'Start a 5 or 10 lap run': '5 veya 10 turluk koşu başlat',
    'The Stable': 'Ahır',
    'Permanent upgrades': 'Kalıcı geliştirmeler',
    'Rules': 'Kurallar',
    'How a run works': 'Bir koşu nasıl işler',
    'Language': 'Dil',
    'Sound on': 'Ses açık',
    'Sound off': 'Ses kapalı',
    'Music on': 'Müzik açık',
    'Music off': 'Müzik kapalı',
    'New run': 'Yeni koşu',
    'Choose your horse': 'Atını seç',
    'Length': 'Uzunluk',
    'Start run': 'Koşuyu başlat',
    'Horse': 'At',
    'Number of laps': 'Tur sayısı',
    'Main menu': 'Ana menü',
    'Race': 'Yarış',
    'Race track: four horses in four lanes': 'Yarış pisti: dört şeritte dört at',
    'Run cash. Lost when the run ends.': 'Koşu parası. Koşu bitince kaybolur.',
    'Quit': 'Çık',
    'Quit run?': 'Koşudan çık?',
    'BRACE!': 'ATLA!',
    'Tap in the gold zone for a perfect jump': 'Kusursuz atlayış için altın bölgeye dokun',
    'Brace': 'Atla',
    'Spur': 'Mahmuz',
    'no hazard near': 'yakında engel yok',
    'NOW!': 'ŞİMDİ!',
    'Recent cards': 'Son kartlar',
    'Cards left in the deck': 'Destede kalan kartlar',
    'Next card: pick a suit': 'Sıradaki kart: bir renk seç',
    'Stake': 'Bahis',
    'Rebet': 'Tekrar bahis',
    'Championship points': 'Şampiyona puanları',
    'Pause': 'Duraklat',
    'Resume': 'Devam',
    'Skip': 'Geç',
    'Paused': 'Duraklatıldı',
    'Shuffling': 'Karıştırılıyor',
    'First card comes out soon.': 'İlk kart birazdan çıkıyor.',
    'Pit stop': 'Mola',
    'Pos': 'Sıra',
    'Pts': 'Puan',
    'pts': 'puan',
    'Call the order': 'Sıralamayı tahmin et',
    'Odds lock when the lap starts': 'Oranlar tur başlayınca kilitlenir',
    'Pit shop': 'Mola dükkanı',
    'Reroll': 'Yenile',
    'The shop opens after lap 1. Every horse starts level: 10 cards per suit and no upgrades.': 'Dükkan 1. turdan sonra açılır. Her at eşit başlar: renk başına 10 kart ve geliştirme yok.',
    'Card table': 'Kart masası',
    'Run complete': 'Koşu tamamlandı',
    'Final standings': 'Final sıralaması',
    'Stable Points': 'Ahır Puanı',
    'Play again': 'Tekrar oyna',
    'Permanent upgrades, paid for with Stable Points. You earn points at the end of every run.': 'Ahır Puanı ile satın alınan kalıcı geliştirmeler. Her koşunun sonunda puan kazanırsın.',
    'Reset all progress': 'Tüm ilerlemeyi sıfırla',
    'Really reset everything?': 'Gerçekten her şey sıfırlansın mı?',
    'BIG WIN': 'BÜYÜK KAZANÇ',
    'MEGA WIN': 'MEGA KAZANÇ',
    'JACKPOT': 'JACKPOT',

    // --- menu / setup
    'Permanent upgrades · {n} Stable Points': 'Kalıcı geliştirmeler · {n} Ahır Puanı',
    '{runs} runs · {champs} won · best {pts} pts': '{runs} koşu · {champs} galibiyet · en iyi {pts} puan',
    'No runs yet.': 'Henüz koşu yok.',
    'You': 'Sen',
    '{n} laps': '{n} tur',
    'about {m} minutes': 'yaklaşık {m} dakika',
    'start with {m}': '{m} ile başla',
    '{n} extra card in your suit': 'rengine {n} ekstra kart',
    '{n} extra cards in your suit': 'rengine {n} ekstra kart',
    '+{v} cruising speed': '+{v} seyir hızı',
    '+{p}% winnings': '%{p} daha fazla kazanç',
    '{p}% cheaper shop': 'dükkan %{p} daha ucuz',
    '+{n} shop slot': '+{n} dükkan yuvası',
    '+{n} shop slots': '+{n} dükkan yuvası',
    '{n} free reroll': '{n} bedava yenileme',
    '{n} free rerolls': '{n} bedava yenileme',
    'a free starting upgrade': 'başlangıçta bedava bir geliştirme',
    'better shop rarity': 'daha iyi dükkan nadirliği',
    '+{p}% bet payouts': 'bahis ödemeleri +%{p}',
    'Every run starts level: 10 cards per suit and no rival upgrades before lap 1. Each horse has its own trait.': 'Her koşu eşit başlar: renk başına 10 kart ve 1. turdan önce rakiplerde geliştirme yok. Her atın kendine özgü bir özelliği var.',
    'Your Stable perks: {list}.': 'Ahır avantajların: {list}.',
    'No Stable perks yet. Finish a run to earn Stable Points.': 'Henüz Ahır avantajın yok. Ahır Puanı kazanmak için bir koşuyu bitir.',

    // --- game HUD
    '{n} cards': '{n} kart',
    '{n} chaos': '{n} kaos',
    'home': 'bitiş',
    'FULL CHARGE · surge +{v}': 'TAM DOLU · atılım +{v}',
    'now +{v} · wait for more': 'şimdi +{v} · daha fazlası için bekle',
    'charging {p}%': 'doluyor %{p}',
    'not next': 'sıradaki değil',
    'likeliest': 'en olası',
    '{p}% · {n} left': '%{p} · {n} kaldı',
    '{m} on the next card. Pays stake × odds if it lands.': 'Sıradaki kartta {m}. Tutarsa bahis × oran öder.',
    'Odds are the exact chance from the cards left. A hit streak fills your Spur.': 'Oranlar, kalan kartlardan hesaplanan kesin şanstır. İsabet serisi Mahmuz’unu doldurur.',
    'Streak ×{n} · next hit +{s} stamina': 'Seri ×{n} · sonraki isabet +{s} dayanıklılık',
    'Streak 0': 'Seri 0',
    'Your calls': 'Tahminlerin',
    'Lap {n} / {m}': 'Tur {n} / {m}',
    'Jack': 'Vale', 'Queen': 'Kız', 'King': 'Papaz', 'Ace': 'As',
    'Chaos card': 'Kaos kartı',
    '{s} surges +{b}. You collect {m}.': '{s} +{b} atılım yaptı. {m} kazandın.',
    'Nobody left to surge. You collect {m}.': 'Atılım yapacak kimse kalmadı. {m} kazandın.',
    'Joker of {s}': '{s} Jokeri',
    '{r} of {s}': '{s} {r}',
    'Home already. Dividend {m}.': 'Zaten bitirdi. Temettü {m}.',
    '{s} already finished.': '{s} zaten bitirdi.',
    '{s} surges +{b}. That one is yours.': '{s} +{b} atılım yaptı. O senin atın.',
    '{s} surges +{b}.': '{s} +{b} atılım yaptı.',

    // --- ticker, floating text, banners
    'Chaos card: {s} surges, you collect {m}': 'Kaos kartı: {s} atılım yaptı, {m} kazandın',
    'Chaos card, you collect {m}': 'Kaos kartı, {m} kazandın',
    'Chaos card: your next-card bets are refunded': 'Kaos kartı: sıradaki kart bahislerin iade edildi',
    'Next-card hit {o} · {m}': 'Sıradaki kart isabet {o} · {m}',
    ' · streak ×{n}': ' · seri ×{n}',
    'HOT STREAK ×{n}': 'SICAK SERİ ×{n}',
    'STREAK ×{n}': 'SERİ ×{n}',
    'Next card was {s} · {m}': 'Sıradaki kart {s} oldu · {m}',
    'SPUR +{v}': 'MAHMUZ +{v}',
    'Spur at {p}% stamina: surge +{v}': '%{p} dayanıklılıkla mahmuz: atılım +{v}',
    'unleashes a full-charge Spur': 'tam dolu Mahmuz’u patlatıyor',
    'stumbles over the hazard': 'engelde tökezliyor',
    'PERFECT +{m}': 'KUSURSUZ +{m}',
    'PERFECT': 'KUSURSUZ',
    'perfect jump {m}': 'kusursuz atlayış {m}',
    'CLEAR': 'GEÇTİ',
    'OOPS': 'EYVAH',
    'HORSESHOE': 'NAL',
    'Lucky Horseshoe: bonus surge': 'Şans Nalı: bonus atılım',
    'JACKPOT {m}': 'JACKPOT {m}',
    'heads': 'tura',
    'tails': 'yazı',
    'Coin of Fate landed {c}: {v} cruising this lap': 'Kader Parası {c} geldi: bu tur seyir {v}',
    'Loaded Dice: {n} extra cards this lap': 'Hileli Zar: bu tur {n} ekstra kart',
    'is sabotaged and surges 40% less this lap': 'sabote edildi, bu tur %40 daha az atılım yapıyor',
    'you finish {o}': '{o} sırada bitirdin',
    'finishes {o}': '{o} sırada bitiriyor',
    'WINNER': 'KAZANAN',
    'GO': 'BAŞLA',
    'START': 'BAŞLA',
    'YOU': 'SEN',
    'FINISH': 'BİTİŞ',
    'NICE LAP': 'GÜZEL TUR',
    '1ST PLACE': '1. SIRA',
    'CHAMPION': 'ŞAMPİYON',

    // --- pit stop
    'Before lap 1': '1. turdan önce',
    'Lap {n} of {m} complete': 'Tur {n} / {m} tamamlandı',
    'On the line': 'Startta',
    'Championship': 'Şampiyona',
    'Level start': 'Eşit başlangıç',
    'Every suit has the same 10 cards and nobody has an upgrade yet, so the odds below are close to even. Call the order and place your first bets, then start the lap.': 'Her rengin aynı 10 kartı var ve kimsenin henüz geliştirmesi yok, bu yüzden aşağıdaki oranlar neredeyse eşit. Sıralamayı tahmin et, ilk bahislerini yap, sonra turu başlat.',
    '{o} this lap': 'Bu tur {o} sıra',
    'Prize': 'Ödül',
    'Speed bonus, {s}s under par': 'Hız bonusu, baremin {s}sn altında',
    'Speed bonus, {s}s over par': 'Hız bonusu, baremin {s}sn üstünde',
    'Dividends, {n} card': 'Temettü, {n} kart',
    'Dividends, {n} cards': 'Temettü, {n} kart',
    'Interest': 'Faiz',
    'Lucky Penny': 'Şans Kuruşu',
    'Hazards: {p} perfect, {c} clear, {s} stumbled': 'Engeller: {p} kusursuz, {c} temiz, {s} tökezleme',
    'Luck windfalls': 'Şans getirileri',
    'Next-card bets, {h} of {n} hit': 'Sıradaki kart bahisleri, {n} bahisten {h} isabet',
    ' (best streak {n})': ' (en iyi seri {n})',
    'Bets, {h} of {n} right': 'Tahminler, {n} tahminden {h} doğru',
    ' (combo ×{c})': ' (kombo ×{c})',
    'on {m}': '· {m}',
    'miss': 'ıska',
    'Net this lap': 'Bu tur net',
    '(you)': '(sen)',
    'Start lap {n} of {m}': 'Tur {n} / {m} başlat',
    'Underdog fund': 'Zayıflara destek fonu',
    '(no suit is starved out of the deck):': '(hiçbir renk desteden silinmez):',
    '+{n} card': '+{n} kart',
    '+{n} cards': '+{n} kart',
    'Rivals at the stop': 'Molada rakipler',
    'Nobody upgraded this time.': 'Bu sefer kimse geliştirme yapmadı.',
    'Rivals upgraded during the stop': 'Rakipler molada geliştirme yaptı',
    'cash {c} · {r} on bets': 'nakit {c} · bahislerde {r}',
    'to spend': 'harcanabilir',
    'Your horse is locked in for 1st': 'Atın 1. sıraya kilitli',
    'Locked': 'Kilitli',
    '{s} for {o}: {p}% chance': '{o} için {s}: %{p} şans',
    'Change stake': 'Bahsi değiştir',
    'wins {m}': 'kazanır {m}',
    '<b>{m}</b> staked on {n} call. ': '{n} tahmine <b>{m}</b> yatırıldı. ',
    '<b>{m}</b> staked on {n} calls. ': '{n} tahmine <b>{m}</b> yatırıldı. ',
    'You are locked in for 1st. Tap a horse to call 2nd, 3rd and 4th. ': '1. sıraya kilitlisin. 2., 3. ve 4. sırayı tahmin etmek için bir ata dokun. ',
    'A wrong call loses its stake. Combo on total winnings: 2 right ×{a}, 3 right ×{b}, 4 right ×{c}. Every correct call also earns 1 Stable Point. You are locked in for 1st, and your horse is the first column.': 'Yanlış tahmin bahsi kaybettirir. Toplam kazançta kombo: 2 doğru ×{a}, 3 doğru ×{b}, 4 doğru ×{c}. Her doğru tahmin ayrıca 1 Ahır Puanı kazandırır. 1. sıraya kilitlisin ve atın ilk sütunda.',
    'Rarity odds this stop: ': 'Bu moladaki nadirlik şansı: ',
    'Owned {n}/{m}': 'Sahip: {n}/{m}',
    'Bought': 'Alındı',
    'Buy': 'Al',
    'Reroll (free)': 'Yenile (bedava)',
    'Reroll {m}': 'Yenile {m}',
    'Next lap: ': 'Sonraki tur: ',
    'No upgrades yet.': 'Henüz geliştirme yok.',
    'Ties lose · ': 'Beraberlik kaybeder · ',
    '{n} hand left this stop': 'bu molada {n} el kaldı',
    '{n} hands left this stop': 'bu molada {n} el kaldı',
    'Higher': 'Daha yüksek',
    'Lower': 'Daha düşük',
    'higher': 'daha yüksek',
    'lower': 'daha düşük',
    'a tie': 'eşit',
    '{m} at stake': '{m} bahiste',
    'Stake {m}': 'Bahis {m}',
    'Deal': 'Dağıt',
    'Second card was {w}. You called {d}: ': 'İkinci kart {w}. Tahminin {d}: ',
    'won {m}': '{m} kazandın',
    'lost {m}': '{m} kaybettin',
    'A card is dealt face up. Call whether the next one is higher or lower. The payout follows the real chance.': 'Bir kart açık dağıtılır. Sıradakinin daha yüksek mi daha düşük mü olacağını tahmin et. Ödeme gerçek şansı izler.',

    // --- run over / stable
    'Champion': 'Şampiyon',
    '{o} overall': 'Genelde {o}',
    'Your suit took the run after {n} laps.': 'Rengin {n} tur sonunda koşuyu aldı.',
    '{s} took the run after {n} laps.': '{s} {n} tur sonunda koşuyu aldı.',
    'Lap points': 'Tur puanları',
    'Champion bonus': 'Şampiyon bonusu',
    'Runner-up bonus': 'İkincilik bonusu',
    'Correct calls': 'Doğru tahminler',
    'Unspent run cash <s>{m}</s> is lost. Run cash never carries over.': 'Harcanmayan koşu parası <s>{m}</s> kaybolur. Koşu parası asla sonraki koşuya geçmez.',
    'Run cash never carries over.': 'Koşu parası asla sonraki koşuya geçmez.',
    '{n} SP': '{n} AP',
    'Level {n} / {m}': 'Seviye {n} / {m}',
    'Maxed': 'Maksimum',
    'Buy · {c} SP': 'Al · {c} AP',

    // --- tiers and kinds
    'Common': 'Yaygın', 'Rare': 'Nadir', 'Epic': 'Epik', 'Legendary': 'Efsanevi',
    'Deck': 'Deste', 'Money': 'Para', 'Luck': 'Şans', 'Betting': 'Bahis', 'Gear': 'Ekipman', 'Next lap': 'Sonraki tur',
    'Hearts': 'Kupa', 'Diamonds': 'Karo', 'Clubs': 'Sinek', 'Spades': 'Maça',

    // --- upgrades (names and descriptions as written in the engine)
    'Stacked Deck': 'Hileli Deste', 'Shuffle 2 extra cards of your suit into the deck.': 'Desteye kendi renginden 2 ekstra kart karıştır.',
    'Second Wind': 'İkinci Nefes', 'Cruising speed +0.07 for the rest of the run.': 'Koşunun geri kalanında seyir hızı +0,07.',
    'Deep Lungs': 'Derin Ciğerler', 'Stamina refills 25% faster, so your Spur is ready sooner.': 'Dayanıklılık %25 daha hızlı dolar, Mahmuz’un daha çabuk hazır olur.',
    'Sure Hooves': 'Sağlam Toynaklar', 'Stumbles over hazards last half as long.': 'Engellerdeki tökezlemeler yarı kadar sürer.',
    'Earn an extra $20 at the end of every lap.': 'Her turun sonunda fazladan $20 kazan.',
    'Scout Lens': 'Gözcü Merceği', 'Before every card, one suit that will NOT come next is marked (two with two lenses). Safer next-card bets.': 'Her karttan önce, sıradaki kartta GELMEYECEK bir renk işaretlenir (iki mercekle iki renk). Daha güvenli sıradaki kart bahisleri.',
    'Sand Trap': 'Kum Tuzağı', 'Remove 5 cards of the points leader from the deck.': 'Puan liderinin 5 kartını desteden çıkar.',
    'Retread': 'Yenileme', 'Swap your 3 lowest cards for fresh cards of rank 8 to Queen.': 'En düşük 3 kartını 8 ile Kız arası yeni kartlarla değiştir.',
    'Bookie’s Friend': 'Bahisçinin Dostu', 'Every bet you win pays 5% more.': 'Kazandığın her bahis %5 fazla öder.',
    'Aces High': 'Yüksek Aslar', 'Add two of your Aces, the biggest normal surge.': 'Rengine iki As ekle, en büyük normal atılım.',
    'Long Stride': 'Uzun Adım', 'Surges fade 10% slower, so speed carries further.': 'Atılımlar %10 daha yavaş söner, hız daha uzağa taşınır.',
    'Court Cards': 'Resimli Kartlar', 'Add a Queen and a King of your suit.': 'Rengine bir Kız ve bir Papaz ekle.',
    'Slipstream': 'Arka Rüzgâr', 'Whenever a rival’s card is drawn, you get a small surge of +0.18.': 'Bir rakibin kartı çekildiğinde +0,18 küçük bir atılım alırsın.',
    'Marked Cards': 'İşaretli Kartlar', 'Your 4 lowest cards each gain 6 ranks, up to Ace.': 'En düşük 4 kartının her biri 6 derece yükselir, en fazla As.',
    'Hurdler': 'Engelci', 'Your horse takes the first hazard of every lap with a perfect jump by itself (two with two).': 'Atın her turun ilk engelini kendi başına kusursuz atlar (ikisiyle ilk iki engeli).',
    'Adrenaline': 'Adrenalin', 'After a Spur you keep 25% of your stamina (50% with two).': 'Mahmuzdan sonra dayanıklılığının %25’ini korursun (ikisiyle %50).',
    'Lucky Horseshoe': 'Şans Nalı', 'Every card drawn has an 8% chance to also surge your horse by +1.6, whatever its suit.': 'Çekilen her kartın, rengi ne olursa olsun, atını ayrıca +1,6 atılım yaptırma şansı %8.',
    'Insurance Policy': 'Sigorta Poliçesi', 'Get 25% of every lost stake back.': 'Kaybedilen her bahsin %25’ini geri al.',
    'Haggler': 'Pazarlıkçı', 'Every shop price is 10% lower.': 'Her dükkan fiyatı %10 daha ucuz.',
    'Counterfeit': 'Sahte Kart', 'Turn 3 cards of the points leader into your suit.': 'Puan liderinin 3 kartını kendi rengine çevir.',
    'Wild Joker': 'Vahşi Joker', 'Add two Jokers in your colours. Each surges harder than an Ace.': 'Rengine iki Joker ekle. Her biri As’tan daha güçlü atılım yaptırır.',
    'Loaded Dice': 'Hileli Zar', 'At the start of every lap roll 1 to 3: that many cards of rank 9 to Ace join your suit for the lap.': 'Her turun başında 1 ile 3 arası zar at: o kadar 9 ile As arası kart o tur için rengine katılır.',
    'Chaos Cards': 'Kaos Kartları', 'Shuffle in 2 Chaos cards. When drawn, one surges a random horse by +5 and pays you $25.': 'Desteye 2 Kaos kartı karıştır. Çekildiğinde biri rastgele bir ata +5 atılım yaptırır ve sana $25 öder.',
    'Slingshot': 'Sapan', 'Whenever a rival surges you gain 5% of that surge.': 'Bir rakip atılım yaptığında o atılımın %5’ini sen kazanırsın.',
    'High Roller': 'Büyük Oyuncu', 'Correct 2nd, 3rd and 4th calls pay 40% more.': 'Doğru 2., 3. ve 4. tahminler %40 fazla öder.',
    'Deep Vault': 'Derin Kasa', 'All cash you win from races is 25% higher.': 'Yarışlardan kazandığın tüm para %25 daha yüksek.',
    'Unspent cash earns 8% at the end of every lap.': 'Harcanmayan para her turun sonunda %8 getirir.',
    'Royal Flush': 'Royal Flush', 'Add a 10, Jack, Queen, King and Ace of your suit.': 'Rengine bir 10, Vale, Kız, Papaz ve As ekle.',
    'Coin of Fate': 'Kader Parası', 'Flip a coin at the start of every lap: heads +2 cruising speed, tails −0.8.': 'Her turun başında yazı tura at: tura seyir hızı +2, yazı −0,8.',
    'Golden Ticket': 'Altın Bilet', 'Your speed bonus and dividends are doubled.': 'Hız bonusun ve temettülerin ikiye katlanır.',
    'Jackpot Deck': 'Jackpot Destesi', 'Every card drawn has a 2% chance to pay you $150.': 'Çekilen her kartın sana $150 ödeme şansı %2.',
    'Hostile Takeover': 'Düşmanca Devralma', 'Turn 5 cards of the points leader into your suit.': 'Puan liderinin 5 kartını kendi rengine çevir.',
    'Grand Slam': 'Büyük Slam', 'Combo bonuses on correct calls grow: 2 right ×1.3, 3 right ×1.8, 4 right ×3.': 'Doğru tahminlerdeki kombo bonusları büyür: 2 doğru ×1,3, 3 doğru ×1,8, 4 doğru ×3.',
    'Cut the Deck': 'Desteyi Kes', 'Your 3 best cards start on top of the deck next lap.': 'En iyi 3 kartın sonraki turda destenin en üstünde başlar.',
    'Head Start': 'Avantajlı Başlangıç', 'Begin next lap 25 units down the track.': 'Sonraki tura pistte 25 birim ileride başla.',
    'Double Dividend': 'Çift Temettü', 'Dividends are doubled next lap.': 'Sonraki tur temettüler ikiye katlanır.',
    'Sabotage': 'Sabotaj', 'The points leader surges 40% less next lap.': 'Puan lideri sonraki turda %40 daha az atılım yapar.',
    'Insurance Slip': 'Sigorta Fişi', 'Get 60% of every lost stake back next lap.': 'Sonraki tur kaybedilen her bahsin %60’ını geri al.',
    'All In': 'Hepsi Bahis', 'Every bet you win pays double next lap.': 'Sonraki tur kazandığın her bahis iki kat öder.',

    // --- Stable perks
    'Deep Pockets': 'Dolu Cepler', 'Start every run with +$40 more cash.': 'Her koşuya +$40 daha fazla parayla başla.',
    'Bigger Winnings': 'Büyük Kazançlar', 'All cash you win in a lap is 6% higher.': 'Bir turda kazandığın tüm para %6 daha yüksek.',
    'Loaded Deck': 'Yüklü Deste', 'Start every run with 1 extra card of your suit in the deck.': 'Her koşuya destede renginden 1 ekstra kartla başla.',
    'Paddock Training': 'Padok Antrenmanı', 'Your horse cruises 0.1 faster in every run.': 'Atın her koşuda 0,1 daha hızlı seyreder.',
    'Shrewd Buyer': 'Kurnaz Alıcı', 'Every shop price is 5% lower.': 'Her dükkan fiyatı %5 daha ucuz.',
    'Wider Shop': 'Geniş Dükkan', 'One more upgrade on offer at every pit stop.': 'Her molada teklifte bir geliştirme daha.',
    'Free Reroll': 'Bedava Yenileme', 'One free shop reroll at every pit stop.': 'Her molada bir bedava dükkan yenilemesi.',
    'Owner’s Pick': 'Sahibin Seçimi', 'Every run begins with one free random upgrade.': 'Her koşu bedava rastgele bir geliştirmeyle başlar.',
    'Winner’s Purse': 'Kazanan Keseni', 'Stable Points earned at the end of a run are 10% higher.': 'Koşu sonunda kazanılan Ahır Puanı %10 daha yüksek.',
    'Lucky Stable': 'Şanslı Ahır', 'Rarer upgrades show up more often in the shop.': 'Nadir geliştirmeler dükkanda daha sık çıkar.',
    'Bookie’s Pal': 'Bahisçi Kankası', 'Every bet you win pays 4% more.': 'Kazandığın her bahis %4 fazla öder.'
  };
  Object.assign(I18n.dict.tr, tr);

  Object.assign(I18n.dict.tr, {
    // --- new upgrades
    'Underdog Sponsor': 'Zayıfın Sponsoru', 'Finishing a lap 3rd or 4th pays you $40 from a sponsor.': 'Bir turu 3. ya da 4. bitirmek sana sponsordan $40 kazandırır.',
    'Grit Amplifier': 'Azim Yükselteci', 'Your Grit, the stamina bonus for trailing the leader, is 60% stronger.': 'Azmin, yani liderin gerisinde kalmanın dayanıklılık bonusu, %60 daha güçlü.',
    'Trap Master': 'Tuzak Ustası', 'Start every lap with a free trap, and traps trip their target 95% of the time.': 'Her tura bedava bir tuzakla başla; tuzaklar hedefini %95 oranında tökezletir.',
    'Echo Chamber': 'Yankı Odası', 'When a card of your suit is drawn, there is a 30% chance the same card comes out again next.': 'Rengindeki bir kart çekildiğinde, aynı kartın hemen ardından tekrar çıkma şansı %30.',
    'Phoenix': 'Anka', 'Once per lap, if you are dead last past halfway: a huge surge and full stamina.': 'Turda bir kez, yarıyı geçince son sıradaysan: dev bir atılım ve dolu dayanıklılık.',
    // --- lap modifiers
    'Mud Run': 'Çamur Koşusu', 'Four hazards per horse, and stumbles last 60% longer.': 'At başına dört engel ve tökezlemeler %60 daha uzun sürer.',
    'Quickdraw': 'Hızlı Çekiliş', 'A card every 1.8 seconds: more surges, faster bets.': 'Her 1,8 saniyede bir kart: daha çok atılım, daha hızlı bahis.',
    'Headwind': 'Karşı Rüzgâr', 'Cruising speed −0.3 for everyone: a longer lap where cards matter more.': 'Herkes için seyir hızı −0,3: kartların daha çok önem kazandığı uzun bir tur.',
    'Clear Track': 'Açık Pist', 'No hazards and cruising speed +0.4: a short, fast lap.': 'Engel yok ve seyir hızı +0,4: kısa, hızlı bir tur.',
    'Golden Lap': 'Altın Tur', 'All race prizes are 1.5× bigger.': 'Tüm yarış ödülleri 1,5 kat büyük.',
    'Chaos Night': 'Kaos Gecesi', '4 Chaos cards are shuffled in. Each pays $25 and surges a random horse.': 'Desteye 4 Kaos kartı karıştırılır. Her biri $25 öder ve rastgele bir ata atılım yaptırır.',
    'Derby Day': 'Derbi Günü', 'The final lap: every place is worth double points.': 'Son tur: her sıra çift puan değerinde.',
    // --- horse traits
    'Sprinter': 'Sprinter', 'Stamina refills 20% faster.': 'Dayanıklılık %20 daha hızlı dolar.',
    'Stayer': 'Uzun Soluklu', 'Surges fade 5% slower.': 'Atılımlar %5 daha yavaş söner.',
    'Steady': 'Dengeli', 'Stumbles last half as long, and +0.03 cruising speed.': 'Tökezlemeler yarı kadar sürer ve seyir hızı +0,03.',
    'Closer': 'Finişçi', '+0.12 cruising speed in the last 40% of a lap.': 'Turun son %40’ında seyir hızı +0,12.',
    // --- set bonuses
    'Card Shark I: your cards surge 6% harder': 'Kart Ustası I: kartların %6 daha sert atılım yaptırır',
    'Card Shark II: your cards surge 14% harder': 'Kart Ustası II: kartların %14 daha sert atılım yaptırır',
    'Thoroughbred I: +0.06 cruising speed': 'Safkan I: seyir hızı +0,06',
    'Thoroughbred II: +0.15 cruising speed': 'Safkan II: seyir hızı +0,15',
    'Tycoon I: race cash +8%': 'Patron I: yarış parası +%8',
    'Tycoon II: race cash +16%': 'Patron II: yarış parası +%16',
    'Sharp I: bet payouts +8%': 'Keskin I: bahis ödemeleri +%8',
    'Sharp II: bet payouts +16%': 'Keskin II: bahis ödemeleri +%16',
    'Fortune I: one more free reroll at every stop': 'Talih I: her molada bir bedava yenileme daha',
    'Fortune II: start every lap with +15 stamina': 'Talih II: her tura +15 dayanıklılıkla başla',
    'Kit: start every lap with +12 stamina': 'Takım: her tura +12 dayanıklılıkla başla',
    'Next ({n}): ': 'Sıradaki ({n}): ',
    // --- badges (trophies)
    'Hot Hand': 'Sıcak El', 'Hit 3 next-card bets in a row in one lap.': 'Bir turda üst üste 3 sıradaki kart bahsini tut.',
    'Saboteur': 'Sabotajcı', 'Trip rivals with 3 traps in one run.': 'Bir koşuda 3 tuzakla rakipleri tökezlet.',
    'Comeback Kid': 'Geri Dönüş Ustası', 'Win a lap right after finishing last.': 'Son bitirdiğin turun hemen ardından bir tur kazan.',
    'Perfectionist': 'Mükemmeliyetçi', 'Land 6 perfect jumps in one run.': 'Bir koşuda 6 kusursuz atlayış yap.',
    'Win a run.': 'Bir koşu kazan.',
    'Underdog': 'Yenilen Taraf', 'Win a run after being last at a pit stop.': 'Bir molada sonuncuyken koşuyu kazan.',
    'Take $300 or more in a single lap.': 'Tek bir turda $300 ya da daha fazla kazan.',
    'Marathon': 'Maraton', 'Finish a 10 lap run.': '10 turluk bir koşuyu bitir.',
    'Clairvoyant': 'Kâhin', 'Call all four places right in one lap.': 'Bir turda dört sıranın hepsini doğru tahmin et.',
    'Daily Rider': 'Günün Jokeyi', 'Finish a Daily Derby.': 'Bir Günlük Derbi’yi bitir.',
    // --- guide
    'The race': 'Yarış', 'Your hands': 'Senin hamlelerin', 'Never out of it': 'Hiç bitmez',
    'Four horses, one per suit. Every few seconds a card is drawn and the horse of that suit surges. You ride one suit and always back it to win.': 'Dört at, her renkten bir tane. Birkaç saniyede bir kart çekilir ve o rengin atı atılım yapar. Bir renge binersin ve her zaman onun kazanacağına oynarsın.',
    'Every lap is a race. Points for the place: 4, 3, 2, 1. Most points after the last lap wins the run.': 'Her tur bir yarıştır. Sıraya göre puan: 4, 3, 2, 1. Son turdan sonra en çok puanı olan koşuyu kazanır.',
    '<b>Spur</b> (S) spends stamina for a surge: a full bar is worth much more than a half bar.': '<b>Mahmuz</b> (S) dayanıklılığı bir atılım için harcar: dolu çubuk, yarım çubuktan çok daha değerlidir.',
    '<b>Brace</b> (Space) when a hazard lights up: tap in the gold zone for a perfect jump.': 'Bir engel yandığında <b>Atla</b> (Boşluk): kusursuz atlayış için altın bölgeye dokun.',
    '<b>Trap</b> (X) drops a trap in front of the leading rival. You earn tokens by finishing 3rd or 4th.': '<b>Tuzak</b> (X) önde giden rakibin önüne tuzak bırakır. 3. ya da 4. bitirerek jeton kazanırsın.',
    'You win cash for your place, for cards of your suit after you finish, and for bets. Spend it on upgrades at the pit stop. <b>Cash left at the end of the run is lost.</b>': 'Sıran, bitirdikten sonra çekilen renk kartların ve bahisler için para kazanırsın. Molada geliştirmelere harca. <b>Koşu sonunda kalan para kaybolur.</b>',
    'Bet on the next card. <b>Peek</b> shows it first, <b>Burn</b> throws it away.': 'Sıradaki karta bahis oyna. <b>Bak</b> önce gösterir, <b>Yak</b> onu çöpe atar.',
    'Trailing charges your <b>Grit</b>: stamina refills faster the further you are behind. Last in the standings? The shop gets bigger.': 'Geride kalmak <b>Azmini</b> doldurur: ne kadar gerideysen dayanıklılığın o kadar hızlı dolar. Puan tablosunda sonuncu musun? Dükkan büyür.',
    'The final lap is <b>Derby Day</b>: every place is worth double points, so nothing is settled until the end.': 'Son tur <b>Derbi Günü</b>: her sıra çift puan değerinde, yani son ana kadar hiçbir şey belli olmaz.',
    'Standard': 'Standart', 'Tough': 'Zor', 'Hard': 'Çok Zor', 'Brutal': 'Acımasız', 'Legend': 'Efsane',
    // --- menu, setup
    'Daily Derby': 'Günlük Derbi', 'Stakes': 'Zorluk', 'How to play': 'Nasıl oynanır',
    'Today: {o} overall, {p} pts. Ride again?': 'Bugün: genelde {o}, {p} puan. Tekrar binmek ister misin?',
    'Same deck for everyone today · you ride {s} · 5 laps': 'Bugün herkes için aynı deste · sen {s} ile yarışıyorsun · 5 tur',
    'Win a run on {s} to unlock': '{s} seviyesinde bir koşu kazanınca açılır',
    'rivals buy more · prizes −{p}% · SP +{s}%': 'rakipler daha çok alır · ödüller −%{p} · AP +%{s}',
    'the normal rules': 'normal kurallar',
    // --- race
    'Trap': 'Tuzak', 'none': 'yok', '{n} token': '{n} jeton', '{n} tokens': '{n} jeton',
    'GRIT +{p}% stamina refill': 'AZİM: dayanıklılık dolumu +%{p}',
    'Peek {m}': 'Bak {m}', 'Burn {m}': 'Yak {m}', 'Next card:': 'Sıradaki kart:', 'See the next card first': 'Önce sıradaki kartı gör',
    'You know the next card. Bets are closed until it is drawn.': 'Sıradaki kartı biliyorsun. Kart çekilene kadar bahisler kapalı.',
    'FINAL LAP · ×2 pts': 'SON TUR · ×2 puan',
    'TRIPPED!': 'TÖKEZLEDİ!', 'stumbles in your own trap': 'kendi tuzağında tökezler', 'trips over your trap!': 'tuzağına takılıp tökezler!',
    'DODGED': 'KAÇTI', 'dodges the trap': 'tuzaktan kaçar', 'TRAP!': 'TUZAK!', 'a trap lies ahead of {s}': '{s} için önde bir tuzak var',
    'ECHO': 'YANKI', 'Echo Chamber: your card goes back in the deck': 'Yankı Odası: kartın desteye geri döner',
    'Peek: the next card is {c}': 'Bak: sıradaki kart {c}', 'Burned the {c}. Peek again to see the new top card.': '{c} yakıldı. Yeni üst kartı görmek için tekrar bak.',
    'PHOENIX': 'ANKA', 'rises like a Phoenix: surge and full stamina': 'Anka gibi yeniden doğar: atılım ve dolu dayanıklılık',
    'DERBY DAY': 'DERBİ GÜNÜ',
    // --- pit stop
    'Sponsor': 'Sponsor', 'Start the final lap · ×2 points': 'Son turu başlat · ×2 puan',
    'Next: the final lap': 'Sıradaki: son tur', 'Next lap modifier': 'Sonraki tur kuralı',
    'Underdog draft': 'Zayıflara seçme hakkı', 'You are {o} in the standings, so this stop gives you {list}.': 'Puan tablosunda {o} sıradasın, bu yüzden bu mola sana şunları verir: {list}.',
    '{n} extra shop slot': '{n} ekstra dükkan yeri', '{n} extra shop slots': '{n} ekstra dükkan yeri',
    'Trap tokens': 'Tuzak jetonları', 'You earned {n} for finishing {o}. ': '{o} bitirdiğin için {n} kazandın. ',
    '{n} ready: press Trap (X) in the next lap to drop one in front of the leading rival.': '{n} hazır: sonraki turda Tuzak (X) tuşuyla önde giden rakibin önüne bir tane bırak.',
    'How you won': 'Nasıl kazandın', 'Why {o}?': 'Neden {o}?',
    'Cards: your suit came up <b>{n}</b> times (about {e} expected). The deck was kind.': 'Kartlar: rengin <b>{n}</b> kez çıktı (yaklaşık {e} beklenirdi). Deste sana nazik davrandı.',
    'Cards: your suit came up only <b>{n}</b> times (about {e} expected). A cold deck.': 'Kartlar: rengin yalnızca <b>{n}</b> kez çıktı (yaklaşık {e} beklenirdi). Soğuk bir deste.',
    'Cards: your suit came up <b>{n}</b> times, about what the deck promised.': 'Kartlar: rengin <b>{n}</b> kez çıktı, destenin vaat ettiği kadar.',
    'Hazards: <b>{n}</b> stumble, and each one costs seconds.': 'Engeller: <b>{n}</b> tökezleme ve her biri saniyelere mal olur.',
    'Hazards: <b>{n}</b> stumbles, and each one costs seconds.': 'Engeller: <b>{n}</b> tökezleme ve her biri saniyelere mal olur.',
    'Hazards: <b>{n}</b> perfect jumps, clean riding.': 'Engeller: <b>{n}</b> kusursuz atlayış, temiz sürüş.',
    'Spur: you never used it, so the stamina went to waste.': 'Mahmuz: hiç kullanmadın, dayanıklılık boşa gitti.',
    'Spur: {n} uses at {p}% charge on average. Waiting for more charge pays off.': 'Mahmuz: {n} kullanım, ortalama %{p} doluluk. Daha fazla dolmasını beklemek karşılığını verir.',
    'Spur: {n} uses at {p}% charge on average. Good timing.': 'Mahmuz: {n} kullanım, ortalama %{p} doluluk. İyi zamanlama.',
    'Traps: <b>{h}</b> of {n} tripped a rival.': 'Tuzaklar: {n} tuzaktan <b>{h}</b> tanesi bir rakibi tökezletti.',
    '{s} took the lap with <b>{n}</b> cards of its suit drawn.': '{s} turu, kendi renginden <b>{n}</b> kart çekilerek aldı.',
    // --- run over, Stable
    'Laps won': 'Kazanılan tur', 'Best lap': 'En iyi tur', 'Cash earned': 'Kazanılan para', 'Perfect jumps': 'Kusursuz atlayış',
    'Stumbles': 'Tökezleme', 'Spurs': 'Mahmuz', 'Traps tripped': 'Tuzağa düşen', 'Peeks / burns': 'Bakış / yakış', 'Best streak': 'En iyi seri',
    'Trophy': 'Rozet', 'Unlocked in the shop: {u}.': 'Dükkanda açıldı: {u}.',
    'Stakes unlocked': 'Zorluk açıldı', 'A harder run that pays more Stable Points.': 'Daha çok Ahır Puanı veren daha zor bir koşu.',
    'Run stats': 'Koşu istatistikleri', 'Daily result': 'Günlük sonuç',
    'Copy result': 'Sonucu kopyala', 'Selected: copy it now': 'Seçildi: şimdi kopyala', 'Copied': 'Kopyalandı',
    'Trophies': 'Rozetler',
    'Trophies are earned once and kept. Some unlock new upgrades in the shop. Highest stakes open: {s}.': 'Rozetler bir kez kazanılır ve saklanır. Bazıları dükkanda yeni geliştirmelerin kilidini açar. Açık en yüksek zorluk: {s}.',
    'Unlocked: {u}': 'Açıldı: {u}', 'Unlocks: {u}': 'Açar: {u}',
    'Got it': 'Anladım', 'Next': 'İleri'
  });

  /* the rules page, written out in Turkish so the grammar stays natural */
  I18n.rules.tr = function (C) {
    const n = I18n.n, tp = C.tierPrice, m = x => '$' + x;
    return '' +
      '<section><h3>Bir koşu</h3><p>Bir renk ve bir uzunluk seç: <b>5 veya 10 tur</b>. Her tur, her renkten bir at olmak üzere dört at arasında pist boyunca tam bir yarıştır. 1., 2., 3. veya 4. bitirmek sırasıyla <b>' + C.points.join(', ') + ' puan</b> kazandırır. Son turdan sonra en çok puanı olan şampiyon olur.</p><p>Her koşu <b>eşit</b> başlar: renk başına 10 kart ve 1. turdan önce rakiplerde geliştirme yok. Tek avantajın Ahır geliştirmeleridir.</p></section>' +
      '<section><h3>Çekiliş</h3><p>Her ' + n(C.drawEvery) + ' saniyede bir kart çekilir. O renkteki at, birkaç saniyede sönen bir <b>atılım</b> alır. Yüksek kartlar daha sert atılım yaptırır, ama her kart küçük bir itiştir; bu yüzden yarışlar yaklaşık bir dakika sürer. Bitiren atlar atılımları yok sayar.</p>' +
      '<div class="vals"><span>2–10 sayı</span><span>V 11</span><span>K 12</span><span>P 13</span><span>A 14</span><span>Joker 17</span></div></section>' +
      '<section><h3>Deste</h3><p>Deste küçüktür: <b>' + (C.copies * 4 * (15 - C.minRank)) + ' kart</b>, renk başına ' + (C.copies * (15 - C.minRank)) + ', dereceler ' + C.minRank + ' ile As arası. Kartlar geri konmadan çekilir; bu yüzden çok çıkan bir renk azalır ve şanssız kalan atların sıradaki kartları alma ihtimali artar. Liderler söner, geride kalanlar şansını bulur. Geliştirmeler bunu <b>tüm koşu</b> için değiştirir: kendi kartlarını ekle, yükselt ya da bir rakibinkini yak ve çal (renk başına asla ' + C.minSuit + ' kartın altına inmez). Her turun başında tüm kartlar toplanır ve <b>yeniden karıştırılır</b>.</p><p><b>Zayıflara destek fonu:</b> her molada, destenin %' + Math.round(C.underdog * 100) + '’inden azına sahip bir renk, bu çizgiyi aşana kadar bedava kart alır (en fazla ' + C.underdogMax + '), böylece hiçbir at koşudan silinmez.</p><p>Her turdan sonra rakipler de bedava geliştirme alır; hangilerini aldıklarını molada görebilirsin.</p></section>' +
      '<section><h3>Dayanıklılık ve Mahmuz</h3><p>Senin ve rakiplerin her atın, tur boyunca dolan bir <b>dayanıklılık</b> çubuğu vardır. <b>Mahmuz</b> (butona dokun ya da <b>S</b> tuşuna bas) hepsini anlık bir atılım için harcar ve atılım dayanıklılıktan çok daha hızlı büyür: dolu bir çubuk, yarım çubuğun yaklaşık ' + Math.round(1 / Math.pow(0.5, C.spurCurve)) + ' katı değerindedir. Daha fazlası için bekle ya da erken git ve iki kez kullan. Rakipler de mahmuzlar; kimi sabırla, kimi hemen, hepsi son düzlükte sprint atar. Dolu çubuk dolmayı bırakır, o yüzden sonsuza dek bekleme.</p></section>' +
      '<section><h3>Engeller</h3><p>Her at tur başına ' + C.hazards + ' engelle karşılaşır: kendi şeridinde çitler ve su birikintileri. Biri erişim mesafesine girdiğinde oyun yavaşlar ve <b>ATLA</b> yanar (dokun, <b>Boşluk</b> ya da <b>B</b> tuşuna bas). <b>Kusursuz atlayış</b> için çubuğun altın ucuna dokun: küçük bir atılım ve $' + C.perfectCash + '. Erken dokunursan güvenle geçersin. Kaçırırsan atın <b>tökezler</b> ve yaklaşık ' + n(C.stumbleT) + ' saniye hızının çoğunu kaybeder. Rakipler engellerinin yaklaşık %' + Math.round(C.aiClear * 100) + '’ini geçer.</p></section>' +
      '<section><h3>Sıradaki kart bahisleri</h3><p>Yarış sırasında <b>sıradaki kartın rengine</b> bahis oynayabilirsin. Oranlar, destede kalan kartlardan hesaplanan kesin şanstır (yüzde olarak gösterilir); deste inceldikçe değişir ve rakamlarla oynayabilirsin: küçük kazançlar için en olası rengi, büyük bir patlama için düşük ihtimalli rengi seç. Korunmak için birkaç renge birden bahis oyna. Kasa %' + Math.round((1 - C.cardEdge) * 100) + ' alır, ama bir <b>isabet serisi</b> Mahmuz dayanıklılığını doldurur ve Gözcü Merceği sıradaki kartta <b>gelmeyecek</b> renkleri işaretler. Bahisler: ' + C.cardStakes.map(m).join(', ') + '. Bir renge bahis için 1–4 tuşlarına bas. Kaos kartı tüm bahisleri iade eder.</p></section>' +
      '<section><h3>Sıralamayı tahmin etme</h3><p>Her turdan önce hangi atın <b>1., 2., 3. ve 4.</b> bitireceğini tahmin eder ve her tahmine bahis koyarsın. Kendi atın <b>1. sıraya kilitlidir</b>: her zaman kendine oynarsın ve yalnızca bahis miktarını değiştirebilirsin. Diğer üç sırayı seçmek ya da atlamak sana kalmış. Bahisçi turu yüzlerce kez simüle eder ve her atın her sıradaki oranını gösterir; yani sürpriz at daha çok öder. Geliştirme aldıkça oranlar değişir ve <b>tur başlayınca kilitlenir</b>.</p><p>Doğru tahmin bahis × oran öder. Yanlış tahmin bahsi kaybettirir. Birkaçını doğru bilirsen toplam ödeme bir <b>kombo</b> ile çarpılır (ikisi için ' + n(C.combo[2]) + '×, üçü için ' + n(C.combo[3]) + '×, dördü için ' + n(C.combo[4]) + '×). Her doğru tahmin ayrıca koşuna <b>1 Ahır Puanı</b> ekler. Bahisçi tek turluk eşyalarını, Mahmuzları ve şans geliştirmelerini hesaba katmaz; avantaj da buradan gelir.</p></section>' +
      '<section><h3>Para</h3><p>Her turdan sonra <b>koşu parası</b> kazanırsın: bitirdiğin sıraya göre bir ödül (' + C.prizes.map(m).join(', ') + '), ' + C.par + ' saniyenin altındaki her saniye için $' + n(C.bonusPerSec) + ' hız bonusu ve <b>temettüler</b>: atın çizgiyi geçtikten sonra çekilen, rengindeki her kart değerinin ' + n(C.divPerValue) + ' katını öder. Bahisler bunların üstüne ödenir.</p><p>Parayı geliştirmelere, yenilemelere, bahislere ve kart masasına harca. <b>Koşu bittiğinde kalan her şey kaybolur.</b></p></section>' +
      '<section><h3>Mola dükkanı ve nadirlikler</h3><p>Dükkan 1. turdan sonra açılır ve ' + C.shopSlots + ' geliştirme sunar. Her geliştirme bir nadirliğe aittir ve <b>bir nadirlikteki tüm geliştirmeler aynı fiyattır</b>: Yaygın $' + tp.common + ', Nadir $' + tp.rare + ', Epik $' + tp.epic + ', Efsanevi $' + tp.legendary + '. Dükkan her nadirliğin şansını gösterir ve koşu ilerledikçe daha nadir geliştirmeler daha sık çıkar. Ücret karşılığında yenileyebilirsin.</p><p>Geliştirme türleri: Deste, At, Para, Bahis, Ekipman (Gözcü Merceği ve Engelci gibi), Şans (rastgele atılımlar, nakit getirileri, zarlar, yazı tura) ve bir kez kullanılan Sonraki tur eşyaları.</p></section>' +
      '<section><h3>Kart masası</h3><p>Her molada en fazla ' + C.tableLimit + ' el <b>daha yüksek mi daha düşük mü</b> oynayabilirsin. Bir kart açılır, sıradakinin daha yüksek mi daha düşük mü geleceğini tahmin edersin; beraberlik kaybeder. Ödeme, küçük bir kasa payıyla gerçek şansı izler.</p></section>' +
      '<section><h3>Yetişme araçları</h3><p>Hiç kimse 3. turda koşudan kopmamalı. <b>Azim:</b> atın bir turda liderin ne kadar gerisindeyse dayanıklılığı o kadar hızlı dolar (en fazla +%' + Math.round(C.gritMax * 100) + '), yani geride kalan at büyük bir Mahmuz biriktirebilir. <b>Tuzaklar:</b> 3. bitirirsen 1, 4. bitirirsen 2 jeton kazanır ve sonraki tur için saklarsın (en fazla ' + C.trapCap + '). Önde giden rakibin önüne bir tane bırakmak için <b>Tuzak</b> (X) tuşuna bas: rakibi yaklaşık %' + Math.round(C.trapHit * 100) + ' oranında tökezletir. <b>Zayıflara seçme hakkı:</b> molada puan tablosunda sonuncuysan fazladan bir dükkan yeri ve bir bedava yenileme alırsın, 3. isen bir bedava yenileme. <b>Derbi Günü:</b> son tur <b>çift puan</b> değerindedir.</p></section>' +
      '<section><h3>Tur kuralları</h3><p>İlk turdan sonraki turların çoğu, molada duyurulan bir kuralla gelir ve bahisçi bunu fiyatlar: Çamur Koşusu (4 engel, daha uzun tökezleme), Hızlı Çekiliş (1,8 saniyede bir kart), Karşı Rüzgâr (daha yavaş seyir), Açık Pist (engel yok, daha hızlı seyir), Altın Tur (ödüller ×1,5) ve Kaos Gecesi (destede 4 Kaos kartı).</p></section>' +
      '<section><h3>Bak ve yak</h3><p>Bir tur sırasında $' + C.peekCost + ' ödeyip destenin en üstündeki kartı görmek için <b>Bak</b>’a basabilirsin. Çekiliş tepki verebilmen için biraz bekler ve kart çekilene kadar sıradaki kart bahisleri kapalıdır. Yalnızca açık bir sıradaki kart bahsin yokken bakabilirsin. Baktıktan sonra kartı $' + C.burnCost + ' karşılığında <b>Yakabilir</b> (tur başına en fazla ' + C.burnMax + ' kez) ve tekrar bakabilirsin.</p></section>' +
      '<section><h3>At özellikleri ve takımlar</h3><p>Her rengin atının kendine özgü bir özelliği vardır: ♥ Sprinter (dayanıklılık %20 daha hızlı dolar), ♦ Uzun Soluklu (atılımlar %5 daha yavaş söner), ♣ Dengeli (tökezlemeler yarı kadar sürer, seyir hızı +0,03), ♠ Finişçi (turun son %40’ında seyir hızı +0,12). Geliştirmeler ayrıca <b>takımlar</b> oluşturur: aynı türden (Deste, At, Para, Bahis, Şans, Ekipman) farklı geliştirmeler edin, takım bir bonus öder ve bu molada görünür.</p></section>' +
      '<section><h3>Rozetler, zorluk ve Günlük Derbi</h3><p><b>Rozetler</b>, üst üste üç kart bahsi tutmak, üç rakibi tuzağa düşürmek ya da geri dönüp kazanmak gibi başarılar için bir kez verilir ve bazıları yeni geliştirmelerin (Yankı Odası, Tuzak Ustası, Anka, Azim Yükselteci) kilidini açar. Bir sonraki <b>zorluk</b> seviyesini açmak için bir koşu kazan: rakipler daha çok geliştirme alır ve ödüller küçülür, ama Ahır Puanı seviye başına %' + Math.round(C.diffSp * 100) + ' artar. <b>Günlük Derbi</b>, o gün herkes için aynı tohum ve aynı atla, Ahır geliştirmesiz beş turluk bir koşudur ve kopyalayıp paylaşabileceğin bir sonuç verir.</p></section>' +
      '<section><h3>Ahır</h3><p>Koşu sonunda <b>Ahır Puanı</b> kazanırsın: tur puanları, doğru tahminler ve şampiyon için tur başına 2, ikinci için tur başına 1 bonus. Bunları Ahır’da kalıcı geliştirmelere harca: başlangıç parası, ekstra kartlar, daha hızlı seyir, daha ucuz dükkanlar, daha iyi nadirlik şansı ve daha iyi bahis ödemeleri. İlerleme bu tarayıcıda saklanır.</p></section>';
  };
})();
